version: "3.7"

services:
  nginx:
    image: nginx:alpine
    ports:
    - "80:80"
    volumes:
    - "./docker/nginx/conf.d:/etc/nginx/conf.d"
    - "./docker/nginx/logs:/var/log/nginx"
    - ".:/var/www/app"

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
    - ".:/var/www/app"
